stocks_data_model:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      threads: 4
      keyfile: "{{ env_var('BIGQUERY_KEYFILE_PATH') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      priority: interactive
